# Generated by Django 3.0.4 on 2022-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
